// Tekstinnhold for de fem produktkonseptene. Tall hentes fra modell.json i bygg.js.
module.exports = {
  glod: {
    tagline: "Varme og en langsom trykkbølge, ingen vibrasjon. Laget for kropper som trenger tid.",
    tegning: "GL-001_Glod.png",
    persona: [
      "**Primær: «Ingrid», 52 år**, i overgangsalder, i parforhold, høy kjøpekraft. Opplever tørrhet, redusert følsomhet og at det tar lengre tid å bli opphisset. Synes dagens produkter er «for brutale» og kalde.",
      "**Sekundær:** kvinner 30–65 med vulvodyni, dyspareuni eller sensitivt vev etter fødsel. Også kvinner etter kreftbehandling (f.eks. aromatasehemmere eller strålebehandling) som har fått råd om å stimulere blodgjennomstrømning.",
      "**Betalingsvilje:** 2 000–3 500 kr. Kjøper diskret på nett eller på apotek og stoler på faglige anbefalinger.",
    ],
    problem: [
      "Markedet består nesten bare av vibrasjon og lufttrykk optimalisert for _rask og kraftig_ stimulering. For tre grupper er det feil virkemiddel: kropper med redusert blodgjennomstrømning (overgangsalder), kropper med smerte (vulvodyni) og brukere som opplever nummenhet etter vibrasjon. Høy intensitet på et lite punkt (10–15 mm munnstykke) gir ubehag eller nummenhet, og mange slutter å bruke produktet.",
      "Fysiologisk starter opphisselse med vasokongestjon, altså økt blodtilførsel til klitoriskomplekset (glans, skaft og bulber under kjønnsleppene). Varme og langsomt, bredt trykk fremmer dette bedre enn høyfrekvent vibrasjon.",
    ],
    ide: [
      "GLØD er en håndflatestor «stein» med en varm, gelfylt kontaktflate (38–41 °C). Under en myk membran beveger en liten rullevogn seg langsomt fram og tilbake (0,3–1,5 Hz, slag 52 mm). Bevegelsen gir en rullende trykkbølge over vulva, omtrent som en varm hånd som stryker. Den aktive sonen er 76 × 36 mm, rundt 20 ganger større enn et typisk munnstykke. Trykket fordeles over hele det ytre klitoriskomplekset i stedet for å konsentreres på glans.",
      "Grunnmodus har ingen vibrasjon. Brukeren kan legge til en svak «hjerteslag»-puls (LRA, 40–80 Hz) for mer intensitet. Programmet «Tidevann» bygger seg gradvis opp over 20 minutter: varme først, deretter langsom bølge, så økende tempo og trykk. Produktet tilpasser seg kroppen, og ikke omvendt.",
    ],
    diff: [
      "Første produkt som kombinerer **varme og mekanisk peristaltikk** (rullende trykkbølge). Konkurrentene bruker vibrasjon, lufttrykk eller passiv varme.",
      "**Bredflate-stimulering** (76 × 36 mm) i stedet for punktstimulering. Utviklet for å unngå nummenhet og overstimulering.",
      "Utviklet med faglig råd fra gynekolog, bekkenbunnsfysioterapeut og sexolog. Gir troverdighet i apotek og helsekanaler, og åpner for en senere vei som medisinsk utstyr (MDR).",
      "Fungerer uten app og uten konto, med full materialdeklarasjon (materialpass med QR).",
    ],
    funksjoner: [
      "Regulert varme 38 / 39,5 / 41 °C. Oppvarming til 38 °C på cirka 90 sekunder.",
      "Rullende trykkbølge med 5 tempo (0,3–1,5 Hz) og 3 trykknivåer (0,5–3,0 N).",
      "Valgfri «hjerteslag»-puls (LRA) med 3 nivåer.",
      "Programmer: Tidevann (20 min oppbygging), Hvile (bare varme og langsom bølge), Fri.",
      "Tre taktile knapper med ulik form (sirkel, trekant, strek) som kan brukes uten å se.",
      "Reiselås, automatisk avslag etter 30 minutter (kan forlenges) og batteri-LED.",
      "Sømløs kontaktflate og IP67. Tåler vask i vann med mild såpe.",
    ],
    specs: [
      ["Dimensjoner", "128 × 68 × 38 mm (L × B × H)"],
      ["Vekt", "185 g ± 10 g"],
      ["Materialer", "Medisinsk LSR Shore 10A (ytterhud), LSR 20A membran, silikongel, PC/ABS chassis (kun internt), POM-mekanikk"],
      ["IP-klasse", "IP67 (IEC 60529)"],
      ["Batteri", "Li-ion polymer 3,7 V 2000 mAh (7,4 Wh) med PCM, IEC 62133-2 / UN38.3"],
      ["Lading", "Magnetisk 2-pins kontakt, 5 V / 1 A via USB-C-kabel, 2,5 t"],
      ["Driftstid", "60 min med varme og bølge, 120 min med bare bølge"],
      ["Støy", "≤ 30 dB(A) @ 30 cm"],
      ["Temperatursikkerhet", "2 × NTC (redundant), maskinvarekutt 43 °C, bimetall-termosikring 45 °C"],
    ],
    ergonomi: [
      "**Form:** konveks rygg som hviler i håndflaten og konkav kontaktsadel (dybde 2,6 mm) som følger vulvas form. Kan klemmes mellom lårene eller legges på en pute og brukes håndfritt.",
      "**Grep:** hele overflaten er myk LSR 10A uten harde kanter. Knappene sitter på ryggen, under tommelen.",
      "**Motorplassering:** girmotoren sitter i enden lengst fra kroppen (støy- og varmeisolert). Batteriet ligger lavt for et stabilt tyngdepunkt.",
      "**Sensorer:** to NTC-er rett under gelputen gir lukket temperatursløyfe. Motorstrøm overvåkes for å oppdage blokkering.",
    ],
    samsvar: [
      "IEC 60335-1 og IEC 60335-2-32 (massasjeapparater, inkl. varmeelementer): overflatetemperatur, unormal drift og enkeltfeilanalyse.",
      "Biokompatibilitet på ferdig hud og membran: ISO 10993-5 (cytotoksisitet), -10 (sensibilisering), -23 (irritasjon). Kategori: overflateutstyr, slimhinne, begrenset varighet.",
      "ISO 3533:2021 (sexleketøy – design- og sikkerhetskrav), REACH vedlegg XVII og SVHC-screening, RoHS.",
      "EMC: EN 55014-1/-2. Ingen radio, så RED gjelder ikke. Batteri: IEC 62133-2, UN38.3, merking etter EU 2023/1542.",
      "Varmetester: kontinuerlig drift ved 40 °C omgivelse, termisk kartlegging (IR-kamera), feil i NTC og MOSFET simuleres.",
      "USA: FCC Part 15B og CPSC (generell produktsikkerhet). FDA-regulering utløses bare ved medisinske påstander (jf. 21 CFR 884.5970). Lanseres derfor med «wellness»-påstander.",
    ],
    prototype: [
      ["Uke 1–3", "Konseptskisser og håndmodeller", "Leire- og skummodeller i 3 størrelser, 6 intervjuer med målgruppen (grep, form, temperaturpreferanse)", "Skisser, Plasticine, PU-skum"],
      ["Uke 3–7", "3D-modell / CAD + simulering", "Parametrisk modell. Termisk simulering av varmefolie og gel. Dimensjonering av motormoment og rullekraft", "Fusion 360 / SolidWorks, SimScale / Ansys"],
      ["Uke 6–12", "Funksjonell α-prototype", "SLA-chassis, CNC-frest POM-mekanikk, støpt silikonhud i 3D-printede former, PCB v0.1 og utviklingskort", "Formlabs Form 4, CNC, platinasilikon (medisinsk grad til testenheter), JLCPCB"],
      ["Uke 12–16", "Benktest = MVP", "Temperaturkartlegging, kraftmåling (lastcelle), støy (dB-måler), driftstid og feiltester", "IR-kamera, Mark-10 kraftmåler, klasse 2 lydmåler"],
      ["Mnd 4–5", "Brukertest runde 1", "12 deltakere, 2 uker hjemmetest, dagbok og intervju", "Se kapittel 5"],
      ["Mnd 5–8", "β-prototype + DFM", "30 enheter fra myk aluminiumsform (LSR). DFM-gjennomgang med fabrikk. Runde 2 med 30 deltakere", "Prototypeform fra produsent (~40–60k kr)"],
    ],
    produksjon: [
      "**Hud og membran:** LSR-sprøytestøping i 2-kavitets stålform (P20/H13). Huden støpes separat og monteres over chassiset med mekanisk leppe og LSR-lim.",
      "**Chassis:** PC/ABS sprøytestøpt, to deler, ultralydsveiset (gir IP67). **Mekanikk:** POM sprøytestøpt.",
      "**Gelpute:** fylles og forsegles i egen fikstur. 100 % lekkasjetest og 100 % varmetest i sluttest.",
      "**Prototyper:** SLA/MJF-print, CNC og silikonstøping i printede former.",
    ],
    verktoy: [["LSR-form hud (2-kav, stål)", 28000], ["Chassis topp/bunn (2 former)", 18000], ["POM-mekanikk (4 deler, familieform)", 8000], ["Gel-fylle- og forseglingsfikstur", 4000], ["Test- og kalibreringsfiksturer", 5000]],
    moq: "1 000 enheter (pilot), deretter 3 000 per ordre. Verktøy: 6–8 uker til T1-prøver.",
    kanaler: [
      "**Fagambassadører:** program for gynekologer, bekkenbunnsfysioterapeuter og sexologer (f.eks. via Norsk forening for klinisk sexologi). Inkluderer demoenheter, faktaark og rabattkode til pasienter. Lav kundeanskaffelseskostnad og høy tillit.",
      "**Apotek og wellness-handel:** pilot i én apotekkjede og utvalgte wellness-butikker, med eget hyllekonsept for «intim helse 45+». Kategorien er åpen for markedsføring der Meta og Google begrenser betalt annonsering.",
      "**Fortjent medieomtale og innhold:** lansering som «den første vibrasjonsfrie stimulatoren», med podkastsamarbeid om overgangsalder, ekspertlive på Instagram og nyhetsbrev. Innholdet skal være medisinsk korrekt og uten skam.",
    ],
    risiko: [
      ["Varmeskade, særlig hos brukere med nedsatt følsomhet (f.eks. diabetisk nevropati)", "Middels", "Høy", "Redundante NTC-er, maskinvarekutt 43 °C, termosikring 45 °C og automatisk avslag. Tydelig advarsel. Enkeltfeiltester etter IEC 60335."],
      ["Trykkbølgen oppleves for subtil", "Middels", "Høy", "Tidlig α-test. Valgfri LRA-puls. Justerbart trykk opp til 3 N. Minstekrav: komfort- og tilfredshetsscore ≥ 5,5/7 før DFM."],
      ["Lekkasje eller punktering av gelpute", "Lav", "Middels", "Gel i stedet for væske, dobbel barriere, 50 000 utmattingssykluser og punkteringstest. All gel er kroppsvennlig silikon."],
      ["Mekanisk støy fra girmotor", "Middels", "Middels", "POM-mot-POM, dempende motoroppheng, motor i enden borte fra kroppen. Mål ≤ 30 dB(A)."],
      ["Grensen mellom medisinsk utstyr og lystprodukt", "Middels", "Middels", "Gjennomgang av alle påstander med regulatorisk rådgiver. Wellness-ordlyd ved lansering, MDR-spor vurderes separat."],
      ["Store aktører kopierer konseptet", "Middels", "Middels", "Prioritert patentsøknad før offentliggjøring, registrert design og rask lansering i fagkanaler."],
    ],
  },

  avtrykk: {
    tagline: "Myk som deig, stiv som en form. Du former den etter kroppen din, og så låser den seg.",
    tegning: "AV-001_Avtrykk.png",
    persona: [
      "**Primær: «Maja», 29 år**, erfaren bruker med 2–4 leketøy. Teknologinysgjerrig, frustrert over at ingenting «treffer» og over nummenhet etter lufttrykkprodukter.",
      "**Sekundær:** kvinner med anatomisk variasjon (stor eller dekkende klitorishette, endringer etter fødsel, asymmetri) og brukere som ønsker håndfri bruk i bestemte stillinger.",
      "**Betalingsvilje:** 1 800–3 000 kr. Kjøper på nett etter anbefaling og omtaler, og legger vekt på design og innovasjon.",
    ],
    problem: [
      "Ingen kropper er like. Plasseringen og størrelsen på klitoris, hvor mye hetten dekker, og formen på kjønnsleppene varierer mye, men alle produkter har én fast geometri. Følgene er at brukeren holder produktet i en anstrengt vinkel, presser hardere (som gir mer nummenhet) eller gir opp. Passform er den gjengangerklagen i anmeldelser av lufttrykk- og bærbare produkter.",
    ],
    ide: [
      "AVTRYKK har en myk ytterhud rundt et kammer fylt med mikroperler. I ulåst tilstand er produktet formbart. Brukeren trykker det mot kroppen, eller former det for en bestemt stilling, og trykker «Lås». En mikropumpe suger luft ut av kammeret, og perlene låser seg mot hverandre (granulær jamming). Prinsippet er det samme som i vakuummadrasser i ambulanser og myke robotgripere. På under 4 sekunder er produktet stivt i nøyaktig den formen. Formen kan lagres som tre profiler.",
      "Fire haptiske noder er fordelt i bladet. Kapasitive sensorer registrerer hvilke noder som faktisk berører huden, og bare de aktiveres. Stimuleringen havner der kroppen er, med lavere støy og strømforbruk. En «anti-tilvenning»-modus flytter fokuset langsomt mellom nodene for å motvirke nummenhet.",
    ],
    diff: [
      "Første intimprodukt med **brukerprogrammerbar fysisk form** (formlås med vakuum og granulat).",
      "**Kontaktstyrte noder:** bare noder i hudkontakt aktiveres, så produktet tilpasser seg kroppen automatisk.",
      "Håndfri bruk etter låsing: kan kiles mellom lårene, mot en pute eller mot en partner.",
      "Høy IP-verdi: mekanismen og kombinasjonen er beskyttbar, og effekten er lett å demonstrere i media og designkonkurranser.",
    ],
    funksjoner: [
      "Formlås på under 4 sekunder, frigjøring på under 1 sekund, 3 lagrede formprofiler.",
      "4 haptiske noder (LRA, 150–230 Hz) med kontaktdeteksjon.",
      "Moduser: Fokus (én node), Bølge (rotasjon), Anti-tilvenning, Fri.",
      "Overtrykkssikring (maks −75 kPa) og mekanisk avlastning.",
      "Ingen app. Formprofilene lagres lokalt.",
      "IP67, sømløs hud.",
    ],
    specs: [
      ["Dimensjoner", "150 × 70 mm, håndtak 48 × 38 × 32 mm, blad 18–22 mm tykt"],
      ["Vekt", "210 g"],
      ["Materialer", "LSR Shore 5A ytterhud, LSR 0,6 mm blære, PP-mikroperler Ø1,5 mm, PC-håndtak (overstøpt)"],
      ["Formlås", "Undertrykk −55 til −70 kPa. Mål: 15–25 × høyere bøyestivhet i låst tilstand"],
      ["Bøyeområde", "±30°, minste radius 40 mm"],
      ["IP-klasse", "IP67"],
      ["Batteri", "Li-ion polymer 3,7 V 1500 mAh med PCM"],
      ["Lading / driftstid", "Magnetisk kontakt, 2 t / 100 min"],
      ["Støy", "≤ 32 dB(A) i drift, ≤ 38 dB(A) i 2 s ved låsing"],
    ],
    ergonomi: [
      "**Stivt håndtak** (48 mm) inneholder pumpe, ventil og batteri, så tyngdepunktet ligger i hånden. **Formbart blad** (100 mm) gjør kontaktflaten personlig.",
      "Stor, forsenket «Lås»-knapp med tydelig klikk. Tre mindre knapper for modus og intensitet.",
      "Typiske former: skålformet (omslutter vulva), kile (håndfri mellom lår) og vinklet (stilling på siden).",
      "Sensorer: MEMS-trykksensor for vakuumregulering og 4-sone kapasitiv kontaktsensor i flex-ryggraden.",
    ],
    samsvar: [
      "IEC 60335-2-32 (massasjeapparater), EMC EN 55014-1/-2, IEC 62133-2, UN38.3, merking etter EU 2023/1542.",
      "ISO 10993-5/-10/-23 på hud. ISO 3533:2021. REACH og RoHS.",
      "Egne interne tester: 10 000 låsesykluser, lekkasjerate under 1 kPa per 10 min, punkteringstest 100 N, innkapsling av granulat (dobbel barriere, falltest 1,5 m).",
      "Kun utvendig bruk (merkes tydelig).",
    ],
    prototype: [
      ["Uke 1–6", "Mulighetsstudie for jamming (fase 0)", "Test av 5 granulater (PP, PS, glass, malt silikon, kaffegrut) i silikonposer. Måling av stivhet, vekt og lyd. Valg av perlestørrelse", "Silikonposer støpt i printede former, håndpumpe, manometer, lastcelle"],
      ["Uke 4–10", "CAD + ventil-/pumpearkitektur", "Bladgeometri, plassering av noder og kanaler, valg av pumpe og ventil", "SolidWorks, hyllevare-membranpumper"],
      ["Uke 8–16", "Funksjonell α", "Utviklingskort, 4 × LRA med haptikkdriver (DRV2605L-klasse), kapasitiv sensing, printet håndtak", "nRF52/STM32 DK, Formlabs"],
      ["Uke 16–20", "Benktest = MVP", "Låsetid, stivhet, lekkasje, støy, driftstid", "Lastcelle, trykklogger, dB-måler"],
      ["Mnd 5–6", "Brukertest runde 1", "12 deltakere: passform, forståelse av låsing, effekt", "Se kapittel 5"],
      ["Mnd 6–10", "β + DFM + runde 2", "30 enheter fra prototypeformer, 30 deltakere", "Myke aluminiumsformer"],
    ],
    produksjon: [
      "**LSR-sprøytestøping** av ytterhud og blære (2 former). Håndtak i PC med overstøping av LSR.",
      "**Perlefylling** på vektstasjon (18 g ± 0,3 g) og forsegling. **100 % trykkfalltest** (lekkasje) og stivhetstest på stikkprøver.",
      "Prototyper: silikonstøping i printede former og SLA-håndtak.",
    ],
    verktoy: [["LSR-form ytterhud (stål)", 30000], ["LSR-form jamming-blære", 15000], ["Håndtak/chassis + overstøping", 15000], ["Ventilhus", 6000], ["Fylle- og lekkasjetestfiksturer", 6000]],
    moq: "1 000 enheter. Verktøy: 8–10 uker til T1, fordi blæren krever flere iterasjoner.",
    kanaler: [
      "**Forhåndsbestilling og venteliste i egen nettbutikk:** demovideo av «form, lås, ferdig» som hovedinnhold. Mange folkefinansieringsplattformer begrenser kategorien, så egen plattform er tryggere.",
      "**Designpriser og teknologimesser:** Red Dot, iF, Merket for god design (DOGA) og CES Innovation Awards. Det gir medieomtale uten annonsebegrensninger.",
      "**Sexologer og seksualundervisere på sosiale medier:** «kroppen din er ikke feil, leketøyet er det» som budskap, med anonymt brukerinnhold om formprofiler.",
    ],
    risiko: [
      ["For lav stivhet i tynt blad", "Middels", "Høy", "Fase 0-mulighetsstudie før CAD. Optimalisering av perleform og -størrelse. Eventuelt fiberlag i blæren."],
      ["Vakuumlekkasje over tid", "Middels", "Høy", "100 % trykkfalltest, automatisk etterpumping, tilbakeslagsventil og 10 000 sykluser i validering."],
      ["Pumpestøy og raslelyd i ulåst tilstand", "Middels", "Middels", "Pumpen går bare ved låsing, lyddemper. Perler med glatt overflate og optimalt fyllvolum."],
      ["Høy kompleksitet og kostnad", "Middels", "Middels", "Forenkling til 3 noder og én ventil i v1 om nødvendig. Mål for COGS < 400 kr ved 10k."],
      ["Brukerne forstår ikke konseptet", "Lav", "Middels", "Hurtigguide, video i emballasjen (QR) og demoenheter i butikk."],
      ["Frihet til å operere (FTO): jamming-patenter i robotikk", "Middels", "Høy", "FTO-analyse før designfrys. Patentsøknaden fokuserer på bruksområde og kombinasjon med kontaktstyrte noder."],
    ],
  },

  samklang: {
    tagline: "En tynn pute som sitter av seg selv og følger rytmen dere har sammen.",
    tegning: "SK-001_Samklang.png",
    persona: [
      "**Primær: «Sara og Jonas», 34 år**, samboere med småbarn og lite tid. Ønsker mer klitorisstimulering under samleie uten å måtte holde noe eller trykke på en fjernkontroll.",
      "**Sekundær:** skeive par (inkl. strap-on og scissoring) og solobrukere som vil ha håndfri bruk. Produktet har ingen innvendig del og passer derfor alle kombinasjoner.",
      "**Betalingsvilje:** 1 300–2 200 kr. Kjøpes ofte som gave (Valentinsdag og jul).",
    ],
    problem: [
      "En stor amerikansk befolkningsstudie (Herbenick mfl., 2018) fant at bare rundt 18 % av kvinnene oppgir at samleie alene er nok for orgasme. Omtrent 37 % sier at klitorisstimulering er nødvendig. Dagens parprodukter har enten en innvendig del som tar plass og glir ut (C-form), eller de faller av (bærbare uten anker). I tillegg må noen holde fjernkontrollen, og det bryter flyten.",
    ],
    ide: [
      "SAMKLANG er en 4–9 mm tynn, buet pute (R60) som legges over vulva og venusberget. Kontaktsiden har en mikrotekstur med cirka 380 sugekopper (Ø0,8 mm), inspirert av blekksprutens sugekopper. Teksturen gir et mildt feste på fuktig hud uten stropper, lim eller innvendig anker. Puten tas av ved å skrelle den av fra spissen.",
      "Trykksensorer i fire soner og en IMU registrerer når partnerens kropp presser mot puten og i hvilken rytme dere beveger dere. Stimuleringen følger automatisk: mer kontakt gir mer intensitet, og bevegelsestempoet styrer pulstempoet. Ingen trenger å holde noe. Den valgfrie fjernkontrollen styres med klemtrykk: hardere grep gir mer.",
    ],
    diff: [
      "**Nytt festeprinsipp i kategorien:** mikro-sugetekstur i stedet for anker, stropp eller lim.",
      "**Responsiv stimulering:** reagerer på partnerens trykk og rytme, så stimuleringen følger det dere gjør.",
      "Ingen innvendig del. Passer alle anatomier og kjønnskombinasjoner, også oralsex og strap-on.",
      "22 g og 4–9 mm tykk, og knapt merkbar mellom kropper.",
    ],
    funksjoner: [
      "Mikro-sugefeste: mål 0,3–0,8 N/cm² skjærfeste på fuktig hud.",
      "4-sone trykkstyring og rytmegjenkjenning med IMU.",
      "Moduser: Følg (automatisk), Konstant, Solo.",
      "Valgfri klemfjernkontroll (BLE) og felles magnetisk ladedokk.",
      "Fungerer uten app. Krypterte BLE-par bare mellom pute og fjernkontroll.",
    ],
    specs: [
      ["Dimensjoner", "78 × 46 mm, tykkelse 9,0 mm (rot) til 4,0 mm (spiss), krumning R60"],
      ["Vekt", "22 g (pute), 28 g (fjernkontroll)"],
      ["Materialer", "LSR Shore 15A med mikrotekstur, TPU 85A fleksramme"],
      ["IP-klasse", "IP67"],
      ["Batteri", "Kurvet LiPo 180 mAh (pute), 100 mAh (fjernkontroll)"],
      ["Lading / driftstid", "Magnetiske pogo-pinner, 60 min / 50–70 min"],
      ["Radio", "BLE 5.x, 0 dBm"],
      ["Støy", "≤ 28 dB(A) @ 30 cm (dempes ytterligere mellom kropper)"],
    ],
    ergonomi: [
      "Dråpeform: bred del (46 mm) over glans og venusberget, smal spiss (18 mm) mot vaginalåpningen.",
      "To flate LRA-er: én over glans, én midt på puten. Elektronikken ligger i den tykke roten.",
      "Fleksramme i TPU gjør at puten følger kroppen, og avskrellingsfliken på spissen gjør den enkel å ta av.",
      "Sensorer: kapasitiv trykkmatrise i 4 soner og en 6-akset IMU.",
    ],
    samsvar: [
      "RED 2014/53/EU: EN 300 328, EN 301 489-1/-17, EN 62479. USA: FCC Part 15C.",
      "ISO 10993-5/-10/-23 (slimhinnekontakt, begrenset varighet). Egen hudtest for mikrosugeteksturen (petekkier og merker) i brukertest.",
      "IEC 62133-2, UN38.3, EU 2023/1542. EMC. ISO 3533. REACH og RoHS.",
      "Mekanisk utmatting: 20 000 bøyesykluser og slitasjetest av tekstur (500 vasker).",
    ],
    prototype: [
      ["Uke 1–4", "Skisser, skummodeller og formstudie", "Formvarianter testes over klær og med partnerstilling (påkledd)", "Skum, leire"],
      ["Uke 3–10", "Mikrotekstur-FoU", "Masterformer i høyoppløselig SLA (25 µm) og laserablasjon. Silikonstøping. Feste- og avskrellingstester på syntetisk hud", "Formlabs Form 4, laserprosessering, Mark-10 kraftmåler, Vitro-Skin"],
      ["Uke 6–14", "CAD + elektronikk", "Rigid-flex-utlegg. Algoritme for trykk og rytme utviklet på opptak fra testrigg", "Altium/KiCad, nRF52 DK, BMI270"],
      ["Uke 14–18", "Funksjonell α = MVP", "10 enheter, benktest av feste, driftstid og BLE gjennom vev", "Fantommodell for BLE"],
      ["Mnd 4,5–6", "Brukertest runde 1", "10 par, 2 uker", "Se kapittel 5"],
      ["Mnd 6–9", "β + DFM + runde 2", "25 par. Teksturinnsats i stål", "Produsentens prototypeformer"],
    ],
    produksjon: [
      "**LSR-sprøytestøping** med lasertekstur- eller EDM-mikrokavitetsinnsats (utskiftbar ståldel). TPU-ramme som innleggsdel (overstøping).",
      "Rigid-flex PCBA. Fjernkontroll i PC + LSR to-komponent.",
      "Prototyper: SLA-masterformer og silikonstøping.",
    ],
    verktoy: [["LSR-form m/ mikroteksturinnsats", 35000], ["TPU-ramme", 10000], ["Fjernkontroll (2 former)", 12000], ["Test- og ladefiksturer", 5000]],
    moq: "2 000 enheter (teksturinnsatsen gjør små serier dyre). Verktøy: 8–10 uker.",
    kanaler: [
      "**Grossist til de store nettbutikkene i Norden og EU** (f.eks. Sinful, Kondomeriet, Amorelie, Lovehoney): parprodukter selger godt i disse kanalene, og butikkene står for trafikken.",
      "**Parterapeuter og samlivskurs:** innhold om «orgasmegapet» og samarbeid med sexologer. Rabattkode til kursdeltakere.",
      "**Gavesesonger:** Valentinsdag- og julepakke med reiseetui og gavekort. Annonsering i søk og podkaster, ikke i Meta.",
    ],
    risiko: [
      ["Festet svikter med glidemiddel, hår eller svette", "Høy", "Høy", "Tidlig FoU-spor med go/no-go i uke 10. Testmatrise med glidemidler. Instruks om vannbasert glidemiddel. Reservefeste: tynn trusestrikk som tilbehør."],
      ["Hudmerker eller irritasjon fra sugekoppene", "Middels", "Middels", "Små kopper (Ø0,8 mm), lav Δp (< 5 kPa). Hudvurdering i brukertest. ISO 10993-10."],
      ["Puten løsner ved kraftig bevegelse", "Middels", "Middels", "Lav masse (22 g), R60-krumning, fleks i TPU-ramme. Testmatrise for stillinger."],
      ["BLE-signal dempes mellom kropper", "Middels", "Lav", "Autonom modus som standard (fjernkontrollen er valgfri). Antenne i rotens kant."],
      ["Teksturen tettes eller er vanskelig å rengjøre", "Lav", "Middels", "Åpen koppgeometri, medfølgende børste og vasketest over 500 sykluser."],
      ["Slitasje på verktøyets teksturinnsats", "Lav", "Middels", "Utskiftbar innsats i herdet stål. Inspeksjon hver 50 000. skudd."],
    ],
  },

  lene: {
    tagline: "Nytelse uten grep. Kroppen styrer, og puten gjør resten.",
    tegning: "LE-001_Lene.png",
    persona: [
      "**Primær: «Hanne», 41 år**, har revmatoid artritt med nedsatt håndkraft og utmattelse. Ønsker en selvstendig seksualitet uten å be om hjelp, og vil ikke ha noe som «ser ut som et hjelpemiddel».",
      "**Sekundær:** personer med MS, CP, ryggmargsskade, kronisk smerte, slitasjegikt eller senskader. Eldre brukere. Alle som vil ha håndfri komfort og bedre stillinger.",
      "**Betalingsvilje:** 1 200–2 000 kr privat. I tillegg kan det finnes offentlig finansiering (NAV har en kategori for seksualtekniske hjelpemidler, som bør undersøkes) og innkjøp gjennom rehabiliteringsinstitusjoner.",
    ],
    problem: [
      "Nesten alle produkter krever grep, finmotorikk, at man holder dem i en vinkel i 10–30 minutter, og at man trykker på små knapper. For personer med nedsatt hånd- eller armfunksjon, smerte eller utmattelse blir solosex utilgjengelig eller avhengig av assistanse. Eksisterende løsninger er generiske kileputer kombinert med vanlige leketøy, og de løser ikke betjeningen.",
    ],
    ide: [
      "LENE er en kilepute (20°) med en skinne innebygd under det vaskbare trekket. En stimuleringsmodul («puck») holdes på plass med magneter gjennom stoffet. Den kan skyves 140 mm langs skinnen med hånden, hoften, albuen eller en pute, og krever aldri grep.",
      "Kroppen styrer intensiteten. Modulen står på en liten luftpute med barometersensor: lener du mer, blir den sterkere, og lener du mindre, blir den svakere. Som alternativ finnes fjernkontrollen «Stein» (Ø90 mm) med tre store knapper i ulik form (sirkel, trekant, strek). Den kan betjenes med knyttneve eller albue og har 6 N aktiveringskraft. Puten fungerer liggende, sittende og i sideleie.",
    ],
    diff: [
      "**Universell utforming fra start:** utviklet sammen med brukerorganisasjoner og testet med ergoterapeut.",
      "**Kroppsstyrt intensitet** (lene-trykk) og **magnetisk posisjonering gjennom tekstil**, ingen av delene finnes i kategorien i dag.",
      "Estetikk som et designmøbel og ikke som medisinsk utstyr. Modulen kan også brukes alene.",
      "Mulig dobbel kanal: forbruker og offentlig sektor (hjelpemiddel).",
    ],
    funksjoner: [
      "Kilepute 20° med sklisikker bunn, trekkløkke og sidelommer.",
      "Magnetisk modul med 12 N holdekraft og 140 mm justering.",
      "Trykkstyrt intensitet (barometer) og «Stein»-fjernkontroll.",
      "Bekreftelse via haptikk og lyd ved hvert trykk (krever ikke syn).",
      "Trekk som tåler vask på 60 °C, vanntett innertrekk og ekstra trekk som tilbehør.",
    ],
    specs: [
      ["Pute", "380 × 300 × 180/40 mm, 20° helning, 1,4 kg, HR-kaldskum 45 kg/m³"],
      ["Trekk", "PES/Tencel med glidelås, 60 °C vask, vanntett TPU-innertrekk, OEKO-TEX Standard 100"],
      ["Modul («puck»)", "Ø62 × 28 mm, 120 g, LSR Shore 10A, IP67"],
      ["Aktuatorer", "Lavfrekvent ERM Ø24 (40–90 Hz «rumble») + LRA"],
      ["Batteri / lading", "Li-ion 1200 mAh / induktiv eller magnetisk ladeplate, 2 t"],
      ["Driftstid", "120 min"],
      ["Fjernkontroll", "Ø90 × 30 mm, 3 taktile knapper (6 N), BLE, oppladbar"],
      ["Støy", "≤ 32 dB(A) @ 30 cm"],
    ],
    ergonomi: [
      "Helningen på 20° vipper bekkenet og legger vulva mot modulen uten at brukeren må holde noe.",
      "Modulens kuppelprofil har ingen kanter. Luftputen gir 6 mm fjæring, som er komfortabelt og fungerer som sensor.",
      "Fjernkontrollens knapper kan skilles bare ved formen. Kontrollen kan ligge i sidelommen eller festes med borrelås.",
      "Trekkløkken gjør det mulig å flytte puten med underarmen.",
    ],
    samsvar: [
      "Modul: RED (EN 300 328, EN 301 489), EMC, IEC 62133-2, UN38.3, ISO 10993-5/-10/-23, ISO 3533.",
      "Skum og tekstil: CertiPUR-EU, OEKO-TEX Standard 100 og antennelighet (EN 597-1/-2 som referanse, California TB 117-2013 for USA).",
      "Magneter: advarsel for pacemaker og ICD, måling av feltstyrke på 15 cm.",
      "Ved salg som hjelpemiddel for funksjonsnedsettelse: vurder MDR klasse I (egenerklæring, lav kostnad) og ta tidlig dialog med NAV om rammeavtale.",
    ],
    prototype: [
      ["Uke 1–3", "Co-design-verksted", "8–10 brukere via brukerorganisasjoner og ergoterapeut. Kartlegging av stillinger, grepsevne og betjening", "Kortsortering, papirprototyper"],
      ["Uke 2–6", "CAD + skumprøver", "CNC-kuttet skum i 3 helninger (15/20/25°), skinne og magnetbærer", "Fusion 360, skumkutter"],
      ["Uke 5–10", "Funksjonell α = MVP (uke 10)", "Innkjøpt kilepute med 3D-printet skinne, modul med utviklingselektronikk og «Stein» i SLA", "Formlabs, nRF52 DK, BMP390"],
      ["Mnd 2,5–3,5", "Brukertest runde 1", "10 deltakere hjemme, med ergoterapeut tilgjengelig", "Se kapittel 5"],
      ["Mnd 3,5–6", "β + DFM + runde 2", "Sydde trekk, modul fra myk form, 20 deltakere", "Systue i EU, LSR-prototypeform"],
    ],
    produksjon: [
      "**Skum:** konfeksjonering (CNC-kutt) hos skumleverandør i Polen eller Baltikum. Nærhet reduserer frakt av voluminøse varer.",
      "**Trekk:** sying i EU eller Asia. **Modul og fjernkontroll:** LSR og PC-sprøytestøping i Shenzhen. Sluttmontering og pakking hos 3PL i EU.",
      "**Rullepakking** (vakuumkomprimert skum) reduserer fraktvolumet med cirka 70 %.",
    ],
    verktoy: [["Modul: LSR-hud + chassis", 28000], ["Fjernkontroll «Stein» (2 former)", 14000], ["Skinne og magnetbærer", 6000], ["Skumform / kuttdyse (valgfritt PU-støp)", 8000], ["Mønster og fiksturer for trekk", 2000]],
    moq: "Skum 500 stk. Modul og fjernkontroll 1 000 stk.",
    kanaler: [
      "**Partnerskap med brukerorganisasjoner** (f.eks. Norsk Revmatikerforbund, MS-forbundet, Norges Handikapforbund, Unge funksjonshemmede): co-design, testpanel og felles kommunikasjon om seksualitet og funksjonsnedsettelse.",
      "**Fagkanal:** ergoterapeuter, rehabiliteringsinstitusjoner og sexologer i rehabilitering. Avklar muligheten for hjelpemiddelordning eller rammeavtale tidlig.",
      "**Bred posisjonering for alle:** «kilepute for bedre stillinger» selges også i ordinær handel. Gir volum og fjerner stigma.",
    ],
    risiko: [
      ["Lite marked og lav margin (stort, tungt produkt)", "Høy", "Høy", "Gjenbruk KJERNE-plattformen i modulen (cirka −25 % BOM). Rullepakking. Institusjonelt salg og tilskudd."],
      ["Høye frakt- og lagerkostnader", "Høy", "Middels", "Skumproduksjon i EU, vakuumpakking og 3PL i Norden."],
      ["Svært ulike brukerbehov", "Middels", "Middels", "Co-design. Størrelsene S og L. Tilbehørskiler. Modulær skinne."],
      ["Hygiene i tekstil", "Lav", "Middels", "Vanntett innertrekk, 60 °C vask og ekstra trekk."],
      ["Magneter og medisinske implantater", "Lav", "Høy", "Advarsel, feltmåling og avstandskrav. Alternativ med borrelåsfeste."],
      ["Usikkerhet om offentlig finansiering", "Middels", "Middels", "Forretningsplanen forutsetter det ikke. Dialog med NAV blir en oppside."],
    ],
  },

  kjerne: {
    tagline: "Én kjerne, mange skall. Bytt batteri selv. Laget for å vare i ti år.",
    tegning: "KJ-001_Kjerne_drivkjerne.png",
    tegning2: "KJ-002_Kjerne_skall.png",
    persona: [
      "**Primær: «Lea», 23 år**, student, klimabevisst, budsjett 500–1 000 kr. Vil ha ett produkt som varer og kan brukes på flere måter.",
      "**Sekundær:** alle som har opplevd at et dyrt leketøy døde da batteriet tok slutt. Gavekjøpere. Bærekraftsbevisste kjøpere i premiumsegmentet som kjøper flere skall.",
      "**Betalingsvilje:** 700–1 200 kr for startsett, 300–450 kr per ekstra skall.",
    ],
    problem: [
      "Sexleketøy er forseglet engangselektronikk. Etter 1–3 år (300–500 ladesykluser) dør batteriet, og hele produktet, inkludert motor, kretskort og silikon, blir avfall. Den som vil ha flere typer stimulering, må kjøpe flere motorer og batterier. Og fordi elektronikken er støpt inn, kan ikke produktet kokes.",
      "EUs batteriforordning (2023/1542, art. 11) krever brukerutskiftbare batterier i bærbare produkter fra februar 2027. Unntaket for apparater beregnet for våte miljøer kan gjelde kategorien, men forbrukerforventningen og kravet om rett til reparasjon går samme vei.",
    ],
    ide: [
      "KJERNE er en IP67-forseglet drivkjerne (Ø24 × 82 mm) med en standard, brukerutskiftbar 14500-celle bak et bajonettlokk med vingegrep. Lokket åpnes uten verktøy. Aktuatoren er en bredbånds voice-coil som gir både dyp «dunk»-stimulering (20–60 Hz) og klassisk vibrasjon (120–250 Hz). Dette er et bredere spekter enn ERM-motoren i de fleste konkurrentprodukter.",
      "Kjernen klikkes inn i skall av kroppsvennlig silikon. Ved lansering finnes **Kuppel** (utvendig), **Bue** (innvendig, G-punkt) og **Stav** (massasje). To kodemagneter i hvert skall leses av Hall-sensorer, og kjernen bytter profil automatisk. Skallene har ingen elektronikk og kan **kokes i 3 minutter**. Nye skall kan lanseres uten ny elektronikk eller sertifisering av radio og batteri.",
    ],
    diff: [
      "Første **reparerbare, modulære plattform** i kategorien: brukerutskiftbart batteri, 10 års garanti på kjernen og reservedeler.",
      "**Voice-coil-aktuator** med en dyp, lavfrekvent følelse som gir mindre nummenhet enn høyfrekvent ERM.",
      "**Skall-ID med automatisk profil.** Skallene kan kokes og er av ett materiale (enkle å resirkulere).",
      "Gjentakende inntekt fra skall og tilbehør, og laveste kostnad per ny produktvariant i porteføljen.",
    ],
    funksjoner: [
      "Batteribytte uten verktøy (bajonettlokk med vingegrep og dobbel O-ring).",
      "Automatisk profil per skall: Kuppel gir dunk og puls, Bue gir bølge, Stav gir dyp rumble.",
      "2 knapper gjennom skallet: + og −, langt trykk for modus.",
      "Reiselås. Kjernen kan brukes alene som minivibrator.",
      "Bytteprogram: send inn et gammelt leketøy (alle merker) og få rabatt.",
    ],
    specs: [
      ["Kjerne", "Ø24 × 82 mm, 62 g inkl. celle, Al 6063-hylse + PC-GF30-hus"],
      ["Aktuator", "Bredbånds voice-coil 20–250 Hz, 1,2 N toppkraft"],
      ["Batteri", "Li-ion 14500, 800 mAh (3 Wh), beskyttet celle, brukerutskiftbar, IEC 62133-2 / UN38.3"],
      ["Lading / driftstid", "Magnetiske pogo-pinner 5 V / 0,5 A, 75 min / 2,5 t"],
      ["IP-klasse", "IP67 (kjerne alene)"],
      ["Støy", "≤ 35 dB(A) @ 30 cm på maks"],
      ["Skall «Kuppel»", "105 × 52 × 48 mm, cirka 85 g, LSR 10A"],
      ["Skall «Bue»", "190 mm totalt, 120 mm innførbar, Ø32 maks, cirka 110 g, LSR 20–30A"],
      ["Skall «Stav»", "175 mm, hode Ø52, håndtak Ø32, cirka 140 g, fleksibel hals LSR 30A"],
    ],
    ergonomi: [
      "Kjernen gir tyngdepunktet i håndtaksdelen av alle skall. Koblingsplaten overfører slaget direkte til skallets kontaktdel.",
      "Knappene er tynne membranfelt i skallet over kjernens knapper, så alle skall har samme betjening.",
      "Vingegrepet på lokket (18 × 4,5 mm) kan åpnes med svak håndkraft.",
      "Sensorer: 2 Hall-sensorer (skall-ID). Fuktdeteksjon på ladepinnene stopper lading når de er våte.",
    ],
    samsvar: [
      "IEC 62133-2 og UN38.3 for cellen. EU 2023/1542: merking, utskiftbarhet (art. 11), innsamling og ansvar for avfallshåndtering.",
      "Frakt av reserveceller: UN3480 (PI965) er strengt regulert i luftfrakt. Selg dem pakket med utstyr (UN3481) eller send dem med vei- eller sjøfrakt.",
      "IEC 60335-2-32, EMC EN 55014-1/-2. Ingen radio.",
      "ISO 10993-5/-10/-23 per skall. ISO 3533. Koketest: 100 sykluser à 3 min ved 100 °C uten degradering.",
      "Bue merkes «kun vaginal bruk», siden den ikke har den brede basen som ISO 3533 krever for anal bruk.",
    ],
    prototype: [
      ["Uke 1–3", "Skisser og arkitektur", "Plattformkrav og skallgrensesnitt (standard for innfesting)", "Skisser, Fusion 360"],
      ["Uke 3–6", "CAD + aktuatorvalg", "Test av 3–4 hyllevare-voice-coils (taktile transdusere). NRE-dialog med leverandør", "Signalgenerator, akselerometer"],
      ["Uke 5–12", "Funksjonell α = MVP (uke 12)", "Dreid aluminiumshylse, SLA-lokk, 14500-holder, PCB v0.1 og 3 skall støpt i printede former", "CNC-dreiebenk, Formlabs, JLCPCB"],
      ["Uke 12–16", "Benktest", "IP67 etter 500 åpninger, driftstid og koblingseffektivitet (akselerometer i skallet)", "Vannbad 1 m, akselerometer"],
      ["Mnd 3–4", "Brukertest runde 1", "15 deltakere, alle 3 skall", "Se kapittel 5"],
      ["Mnd 4–6,5", "β + DFM + runde 2", "30 deltakere, skall fra myke former", "Prototypeformer"],
    ],
    produksjon: [
      "**Kjernehus:** PC-GF30 sprøytestøpt, ekstrudert aluminiumsrør kappet og anodisert, O-ringer kjøpt inn. **Skall:** LSR-sprøytestøping, 3 former (1–2 kaviteter).",
      "Sluttest: 100 % IP-test (trykkfall) og aktuatorkurve. Celler kjøpes fra kvalifisert leverandør med UN38.3-rapport.",
      "Prototyper: CNC-dreide hylser, SLA og silikonstøping.",
    ],
    verktoy: [["Kjernehus + lokk (2 former)", 20000], ["Voice-coil NRE (leverandør)", 8000], ["Skall Kuppel / Bue / Stav (3 LSR-former)", 45000], ["IP- og sluttestfiksturer", 6000]],
    moq: "Kjerne 2 000 enheter. Skall 1 000 per variant. Celler etter leverandørens MOQ (typisk 5 000).",
    kanaler: [
      "**Bytteprogram ved lansering:** «Send inn det gamle leketøyet ditt, få 200 kr i rabatt». Gir PR, data og grønn profil. Innsamlingen skjer gjennom en godkjent EE-returordning.",
      "**Skall-klubb:** valgfritt abonnement med fire skall eller fargeslipp i året (299 kr per stk). Gir gjentakende inntekt og grunn til å komme tilbake.",
      "**Medieomtale om rett til reparasjon:** «det første sexleketøyet du kan reparere selv». Rettes mot forbrukerjournalistikk, miljøorganisasjoner og studentkanaler. Studentrabatt.",
    ],
    risiko: [
      ["O-ringtetting svikter etter mange åpninger", "Middels", "Høy", "Dobbel O-ring, ekstra O-ringsett i esken, 500 åpninger i validering og fuktdeteksjon."],
      ["Brukeren setter inn feil eller uoriginal celle", "Middels", "Høy", "Kontaktgeometri tilpasset beskyttet celle med riktig lengde, PCM-sjekk i fastvare og tydelig merking. Bare godkjente celler selges."],
      ["Kostnad og effekt for voice-coil", "Middels", "Middels", "NRE med leverandør. Klasse-D-driver med høy virkningsgrad. Reservevalg: LRA + ERM."],
      ["Effekttap mellom kjerne og skall", "Middels", "Middels", "Koblingsplate, presspasning og måling av kobling i hver β-runde."],
      ["Lavpris-oppfatning eller kannibalisering", "Lav", "Middels", "Premium skallslipp og designsamarbeid. Kjernen markedsføres som «investering i 10 år»."],
      ["Fraktrestriksjoner for reserveceller", "Middels", "Lav", "Pakket med utstyr eller veifrakt. Salg via nordisk 3PL."],
    ],
  },
};
